<div class="col-main">
<div class="page-title">
    <h1>Feedback</h1>
</div>
<?php //TODO: ?>
<form action="<?php echo Mage::getUrl('asknfeedback/index/post/') ?>" id="feedbackForm" method="post" _lpchecked="1">
    <div class="fieldset">
        <h2 class="legend">Information</h2>
        <ul class="form-list">
            <li class="fields">
                <div class="field">
                    <label for="name" class="required"><em>*</em>Name</label>
                    <div class="input-box">
                        <input name="name" id="name" title="Name" value="" class="input-text required-entry" type="text">
                    </div>
                </div>
                <div class="field">
                    <label for="email" class="required">Email</label>
                    <div class="input-box">
                        <input name="email" id="email" title="Email" value="" class="input-text validate-email" type="text">
                    </div>
                </div>
            </li>
            <li class="wide">
                <label for="comment" class="required"><em>*</em>Feedback</label>
                <div class="input-box">
                    <textarea name="feedback" id="feedback" title="Feedback" class="required-entry input-text" cols="5" rows="3"></textarea>
                </div>
            </li>
        </ul>
    </div>
    <div class="buttons-set">
        <p class="required">* Required Fields</p>
        <input type="text" name="hideit" id="hideit" value="" style="display:none !important;">
        <button type="submit" title="Submit" class="button"><span><span>Send</span></span></button>
    </div>
</form>
<script type="text/javascript">
//<![CDATA[
    var contactForm = new VarienForm('feedbackForm', true);
//]]>
</script>
</div>