<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/LICENSE-M1.txt
 *
 * @category   AW
 * @package    AW_Advancednewsletter
 * @copyright  Copyright (c) 2008-2010 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/LICENSE-M1.txt
 */
?>
<div class="block an-subscribe an-subscribe-ajax" id="advancednewsletter-subscribe-ajax">
    <form action="<?php echo $this->getUrl('advancednewsletter/index/subscribe', array('_secure'=>Mage::app()->getStore(true)->isCurrentlySecure())) ?>" method="post" id="advancednewsletter-form">
        <div class="block-title">
            <div><strong><span><?php echo $this->__('Newsletter') ?></span></strong></div>
            <div>
                <a href="#"><img id="advancednewsletter-cancel" onclick="return false;" src="<?php echo $this->getSkinUrl('images/btn_window_close.gif'); ?>" /></a>
            </div>
        </div>
        <div class="block-content">
            <div class="an-segments">
                <?php echo $this->getChildHtml('advancednewsletter.options.'.Mage::getStoreConfig(AW_Advancednewsletter_Block_Subscribe::STYLES_PATH)); ?>
            </div>
            <div>
                <?php echo $this->getChildHtml('advancednewsletter.subscriber.data') ?>
            </div>
            <div class="an-buttons">
                <button onclick="advancednewsletterForm.submit()" class="button"><span><span><?php echo $this->__('Subscribe') ?></span></span></button>
            </div>
        </div>
    </form>
</div>