<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/LICENSE-M1.txt
 *
 * @category   AW
 * @package    AW_Advancednewsletter
 * @copyright  Copyright (c) 2008-2010 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/LICENSE-M1.txt
 */
?>
<?php if ($this->checkDisplay()): ?>
    <?php if ($this->getData('in_block_only')): ?>
        <?php echo $this->getChildHtml('advancednewsletter.subscribe') ?>
    <?php else: ?>
        <?php if (Mage::helper('advancednewsletter')->isAjaxSubscribeBlock()): ?>
            <?php echo $this->getChildHtml('advancednewsletter.subscribe.link') ?>
        <?php else: ?>
            <?php echo $this->getChildHtml('advancednewsletter.subscribe') ?>
        <?php endif; ?>
    <?php endif; ?>
<?php else: ?>
    <div class="form-subscribe an-subscribe">
        <div class="block-content">
            <?php echo Mage::helper('advancednewsletter')->__('Sorry, the subscription is not available from this page'); ?>
        </div>
    </div>
<?php endif; ?>
