<?php
/**
 * @see Mage_Adminhtml_Block_Sales_Items_Column_Name
 */
?>

<?php if ($_item = $this->getItem()): ?>
    <h5 class="title"><span id="order_item_<?php echo $_item->getId() ?>_title"><?php echo $this->htmlEscape($_item->getName()) ?></span></h5>
    <div><strong><?php echo $this->helper('sales')->__('SKU') ?>:</strong> <?php echo implode('<br />', Mage::helper('catalog')->splitSku($this->htmlEscape($this->getSku()))); ?></div>
    <?php if ($this->getOrderOptions()): ?>
        <dl class="item-options">
        <?php foreach ($this->getOrderOptions() as $_option): ?>
            <?php if( $_option['label'] === 'SPH (Sphere) right') { echo '<br />'; } ?>
            <dt><?php echo $_option['label'] ?>:</dt>
            <dd>
            <?php if (isset($_option['custom_view']) && $_option['custom_view']) { ?>
                <?php echo $this->getCustomizedOptionValue($_option); ?>
            <?php } elseif ($_option['option_type'] == 'area' && $_option['label'] == 'Description') { ?>
				<?php echo nl2br($_option['value']); ?>
			<?php } else { ?>
                <?php echo nl2br($this->escapeHtml($_option['value'])); ?>
                <?php Mage::helper('core/string')->truncate($_option['value'], 55, '', $_remainder);?>
                <?php if ($_remainder):?>
                    ... <span id="<?php echo $_id = 'id' . uniqid()?>"><?php echo $_remainder ?></span>
                    <script type="text/javascript">
                    $('<?php echo $_id ?>').hide();
                    $('<?php echo $_id ?>').up().observe('mouseover', function(){$('<?php echo $_id ?>').show();});
                    $('<?php echo $_id ?>').up().observe('mouseout',  function(){$('<?php echo $_id ?>').hide();});
                    </script>
                <?php endif;?>
            <?php };?>
            </dd>
            <?php if( in_array($this->htmlEscape($_option['label']), array('Near/Add right','Near/Add left')) ){ echo '<br />'; } ?>
        <?php endforeach; ?>
        </dl>
    <?php endif; ?>
    <?php echo $this->htmlEscape($_item->getDescription()) ?>
<?php endif; ?>
