<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/LICENSE-M1.txt
 *
 * @category   AW
 * @package    AW_Advancednewsletter
 * @copyright  Copyright (c) 2008-2010 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/LICENSE-M1.txt
 */
?>
<?php $i=0; ?>
<?php if ($this->displayLabel()): ?>
    <label for="an-segments" class="an-data"><?php echo $this->__('Select lists') ?><span class="required">*</span></label>
<?php endif; ?>
<ul class="an-radio an-data" id="an-segments">
<?php foreach ($this->getSegments() as $segment): ?>
    <?php $segment->isSelected($this->getCategoryId()) == true ? $checked='checked="checked"' : $checked=''; ?>
    <li>
        <input <?php echo $checked; ?> type="radio" name="segments_select[]" id="an-segment-<?php echo $segment->getCode() ?>" value="<?php echo $segment->getCode(); ?>" />
        <label for="an-segment-<?php echo $segment->getCode() ?>"><?php echo $segment->getTitle(); ?></label>
    </li>
<?php endforeach; ?>
</ul>