<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/LICENSE-M1.txt
 *
 * @category   AW
 * @package    AW_Advancednewsletter
 * @copyright  Copyright (c) 2008-2010 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/LICENSE-M1.txt
 */
?>
<div class="col2-set">
    <div class="col-1">
        <div class="inner-head">
            <h5><?php echo $this->__('Contact Information') ?></h5>
            <a href="<?php echo $this->getUrl('customer/account/edit') ?>"><?php echo $this->__('Edit') ?></a>
        </div>
        <p>
            <?php echo $this->htmlEscape($this->getCustomer()->getName()) ?><br />
            <?php echo $this->htmlEscape($this->getCustomer()->getEmail()) ?><br />
            <a href="<?php echo $this->getChangePasswordUrl() ?>"><?php echo $this->__('Change Password') ?></a>
        </p>
    </div>
    <?php if( Mage::helper('advancednewsletter')->extensionEnabled('AW_Advancednewsletter') ): ?>
    <div class="col-2">
        <div class="inner-head">
            <h5><?php echo $this->__('Newsletters') ?></h5>
            <a href="<?php echo $this->getUrl('advancednewsletter/manage') ?>"><?php echo $this->__('Edit') ?></a>
        </div>
        <p>
            <?php if( $this->getCustomerSegmentsTitles() ): ?>
                <?php echo $this->__("You are currently subscribed to ").$this->getCustomerSegmentsTitles() ?>
            <?php else: ?>
                <?php echo $this->__('You are currently not subscribed to any newsletter.') ?>
            <?php endif; ?>
        </p>
    </div>
    <?php endif; ?>
</div>
<br />
