<div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('catalog')->__('Images') ?></h4>
    </div>
    <div class="last" style="padding:8px">
        <div id="fileupload">
            <form action="<?php echo $this->getUrl('rotate360/img360/do/id/' . Mage::app()->getRequest()->getParam('id') ) ?>" method="POST" enctype="multipart/form-data">
                <div class="fileupload-buttonbar">
                    <input type="file" name="files[]" multiple>
                    <button type="submit" class="start">Start upload</button>
                    <button type="reset" class="cancel pv-cancel">Cancel upload</button>
                    <!--<button type="button" class="delete pv-delete">Delete files</button>-->
                </div>
            </form>
            <div class="fileupload-content">
                <table class="files">
                    <tr class="list-header">
                        <td></td>
                        <td>Name</td>
                        <td>Order</td>
                        <td>Size</td>
                        <td colspan="2"></td>
                        <td>Action</td>
                    </tr>
                </table>
                <div class="fileupload-progressbar"></div>
            </div>
        </div>
        <script id="template-upload" type="text/x-jquery-tmpl">
            <tr class="template-upload{{if error}} ui-state-error{{/if}}">
                <td class="preview"></td>
                <td class="name">{{if name}}${name}{{else}}Untitled{{/if}}</td>
                <td class="title">
                    <label><input name="title[]" value="${ctitle}" tabindex="${ctitle}" required /></label>
                </td>
                <td class="size">${sizef}</td>
                {{if error}}
                    <td class="error" colspan="2">Error:
                        {{if error === 'maxFileSize'}}File is too big
                        {{else error === 'minFileSize'}}File is too small
                        {{else error === 'acceptFileTypes'}}Filetype not allowed
                        {{else error === 'maxNumberOfFiles'}}Max number of files exceeded
                        {{else}}${error}
                        {{/if}}
                    </td>
                {{else}}
                    <td class="progress"><div></div></td>
                    <td class="start"><button>Start</button></td>
                {{/if}}
                <td class="cancel"><button>Cancel</button></td>
            </tr>
        </script>
        <script id="template-download" type="text/x-jquery-tmpl">
            <tr class="template-download{{if error}} ui-state-error{{/if}}">
                {{if error}}
                    <td></td>
                    <td class="name">${name}</td>
                    <td class="size">${sizef}</td>
                    <td class="error" colspan="2">Error:
                        {{if error === 1}}File exceeds upload_max_filesize (php.ini directive)
                        {{else error === 2}}File exceeds MAX_FILE_SIZE (HTML form directive)
                        {{else error === 3}}File was only partially uploaded
                        {{else error === 4}}No File was uploaded
                        {{else error === 5}}Missing a temporary folder
                        {{else error === 6}}Failed to write file to disk
                        {{else error === 7}}File upload stopped by extension
                        {{else error === 'maxFileSize'}}File is too big
                        {{else error === 'minFileSize'}}File is too small
                        {{else error === 'acceptFileTypes'}}Filetype not allowed
                        {{else error === 'maxNumberOfFiles'}}Max number of files exceeded
                        {{else error === 'uploadedBytes'}}Uploaded bytes exceed file size
                        {{else error === 'emptyResult'}}Empty file upload result
                        {{else}}${error}
                        {{/if}}
                    </td>
                {{else}}
                    <td class="preview">
                        {{if thumbnail_url}}
                            <a href="${url}" target="_blank"><img width="100" src="${thumbnail_url}"></a>
                        {{/if}}
                    </td>
                    <td class="name">
                        <a href="${url}"{{if thumbnail_url}} target="_blank"{{/if}}>${name}</a>
                    </td>
                    <td class="title">${title}</td>
                    <td class="size">${sizef}</td>
                    <td colspan="2"></td>
                {{/if}}
                <td class="delete">
                    <button data-type="${delete_type}" data-url="${delete_url}">Delete</button>
                </td>
            </tr>
        </script>
       
    </div>
</div>
